env:
  browser: true
  es6: true

extends: airbnb-base

rules:
  no-mixed-operators: 0
  no-console: 0
  no-shadow: 0
  consistent-return: 0
  no-alert: 0
  no-unused-expressions: 0
  no-restricted-syntax: 0

